@startuml

"сторонний код" -> менеджер : добавить элемент интерфейса

' нужно добавить во все обработчики, во все флоу

opt если запущено
' отрисовать элемент, если программа запущена
менеджер -> "элемент интерфейса" : уведомить о нарисовке
менеджер -> художник : запрос на отрисовку
end

@enduml