@startuml
'https://plantuml.com/sequence-diagram

start

if (Key = specialKey?) is (yes) then
    : SpecialKeyPressed.Invoke();
    kill
endif

if (_successor) is (not null) then
    :_successor.HandlePressedKey();
    kill
endif
  
if (IsNeededToChangeFocus) then

endif

stop

@enduml