@startuml

"элемент итерфейса" -> "элемент итерфейса" : метод Redraw
"элемент итерфейса" -> "элемент итерфейса" : преобразует запрос
"элемент итерфейса" --> "контейнер" : вызов события Redraw

' если есть контейнер, иначе сразу к менеджеру. 
' Вообще элемент интерфейса даже не знает, куда отправляет запрос.

"контейнер" -> "контейнер" : преобразует запрос
"контейнер"  --> менеджер : вызов события Redraw

менеджер -> менеджер : преобразует запрос
менеджер -> художник : запрос на отрисовку


@enduml