@startuml

"вызывающий код" -> менеджер : запускает интерфейс
менеджер --> "вызывающий код" : возвращает поток
менеджер -> менеджер : обрабатывает начало
менеджер -> "элемент интерфейса" : запрашивает представление
"элемент интерфейса" -> менеджер : возвращает представление
менеджер -> художник : рисует
менеджер -> менеджер : запускает поток с обработчиком нажатий клавиш
менеджер -> менеджер : запускает обработку запросов в цикле 

@enduml
